### ISSUE TITLE
[Bug] Changing device

### ISSUE THREAD

**Issue by StevenAlexander44** [wseemann/RoMote#36] opened 2024-08-15 14:54 UTC
Changing device doesn't work until the app is closed and re-opened. Also, can you add volume to all roku devices so I can use CEC?

Thank you for keeping the app updated :)

**Comment by wseemann** [comment] 2024-08-27 08:56
Hi @StevenAlexander44, thanks for the bug report. I'm currently unable to reproduce this issue on my phone. Are you running the [latest version](https://github.com/wseemann/RoMote/releases/tag/v1.0.26)? Did you see the same issue in version 1.0.25?

**Comment by StevenAlexander44** [comment] 2024-08-27 17:26
Yes, I am using the latest version (on Lineage 21)
The IP changes, but the name (58") and remote layout (not applicable with this, only with tv vs hdmi) don't change:

https://github.com/user-attachments/assets/77c6d581-d9c0-484d-8c98-3e7b1781aa89

**Comment by wseemann** [comment] 2024-09-25 12:29
Thank you for the bug report. This is fixed in version 1.0.27.

**Closed by wseemann** 2024-09-25 12:29 UTC
